### ISSUE TITLE
Block Template Wide With Cover Image off Center 

### ISSUE THREAD

**Issue by saragreenlaw** [brandid/hello-pro#1]
When using the block template and the wide with cover image the image is off centered. 

![Screen Shot 2019-09-23 at 8 17 10 PM](https://user-images.githubusercontent.com/6663757/65471934-29606580-de3f-11e9-9cef-ce58d581b16a.png)

**Comment by alexmustin** [comment]
Thanks for posting this @saragreenlaw !

I am not seeing this happening on the default Hello! Pro theme:
https://demo.hellopro.personalbranding.thebrandid.com/gutenberg-core-blocks-common-blocks/

Is this happening on all 'wide' blocks?

If it's just this one, I think I may know what is happening.

- The default `.entry-content` container of the Blocks is set to be **660px** max-width.
- The default `.align-wide` blocks are set to be **1020px** max-width. They use negative margins on either side to "break out" of the default container and achieve a wider width.
- The default `.full-width` blocks are sized differently without using the negative margins, and instead are calculated using `vw` measurement units.

If you've specified this block to have a different max-width, then you'll need to also adjust the negative margins on either side (using the difference between the 660px default width and the max-width of your block) -- this will make the block be your max-width but also centered in its container.

For example, if you want the block to be 1200px, I would change the CSS as follows:
```
@media screen and (min-width: 1200px) {
    .full-width-content .site-container .alignwide {
        margin-left: -270px;
        margin-right: -270px;
        max-width: 1200px;
    }
}
```

660px (default) + 270px (left margin) + 270px (right margin) = 1200px

Please let me know if I'm on the right track.

Thanks!

**Comment by saragreenlaw** [comment]
@alexmustin I am not sure if that is the issue. 
It seems to be doing the same [here ](http://brandidsupport.staging.wpengine.com/brand-color/)
This is the Media & Text block and by default, it is set to wide width. There is no option to update the content width. If I switch to the default template it seems to be right.

**Comment by alexmustin** [comment]
Hey @saragreenlaw - it looks like on that site the default blocks are 960px wide.

On that site, you'll need to adjust the width of the "wide" blocks so they are wider than 1020px and have different margins.

For example - let's say you wanted all "wide" blocks to be as wide as the `.site-header .wrap` element: 1200px.

You'd change the CSS in `front-end.css`, around Line 927,  to be:

```
.full-width-content .site-container .alignwide,
.full-width-content .site-container table.alignwide {
    margin-left: -120px;
    margin-right: -120px;
    max-width: 1200px;
}
```
960px (default width) + 120px (left margin) + 120px (right margin) = 1200px

Don't forget to move up the chain of media queries and adjust the widths accordingly for each breakpoint.
