### ISSUE TITLE
Block Template Site Inner Spacing

### ISSUE THREAD

**Issue by saragreenlaw** [brandid/hello-pro#2]
When using the block template there is no spacing between the header and the site inner. You have to add a spacer is there a better way to do this?  Do we have the spacing information in the docs for users? 

![Screen Shot 2019-09-23 at 8 19 26 PM](https://user-images.githubusercontent.com/6663757/65472027-878d4880-de3f-11e9-8784-a02d6988174c.png)

**Comment by alexmustin** [comment]
It looks like this is an issue with the CSS. I will fix it.

The CSS is currently:
```
.page-template-blocks main.content {
    padding-top: 0;
    padding-bottom: 0;
}
```

... but it should be updated to be:
```
.page-template-blocks main.content {
    padding-bottom: 0;
}

.home.page-template-blocks main.content {
    padding-top: 0;
}
```
