### ISSUE TITLE
Genesis Page Layout setting is disabled/missing in Page Editor

### ISSUE THREAD

**Issue by alexmustin** [brandid/hello-pro#3]
There is an issue with not being able to choose the Genesis Page Layout setting on each page when using the Page Editor.

- If the user selects the "Content/Sidebar" layout under Genesis settings in the Customizer, the Sidebar will display on pages by default. 

- If the user selects the "Blocks" page template on a page, it will force the page to be full-width, regardless of the Customizer layout setting.

This is not obvious to users. 

**Current behavior:**
The Genesis Layout Settings panel is missing from the Page Editor. Because of this, the user cannot deviate from the page layout set in the Customizer.

**Expected behavior:**
The user should be able to use the Genesis Layout Settings on each page.

Screenshot of the missing Genesis Layout Settings panel:
https://p47.f4.n0.cdn.getcloudapp.com/items/YEu874dN/Image+2019-09-23+at+7.14.50+PM.png?v=bc3093f3455aee61fa7bf8359b6af9ce

**Comment by saragreenlaw** [comment]
I am also seeing the issue even if choosing full-width layout under Genesis settings in the Customizer, the Sidebar will display on pages by default.

**Comment by alexmustin** [comment]
I think this issue is not a bug, but merely a new feature in Genesis we were unaware of.

In Genesis 3.1.2, the Page Layout setting has been moved into a new Genesis panel in the Block Editor -- see screenshot:
![image](https://user-images.githubusercontent.com/1307497/65638029-24fc8f80-df9a-11e9-8c8a-919ecd0c0c50.png)

If you don't see the Genesis panel, click the 3 dots on the far right, then click on **Genesis** under the Plugins section:
![image](https://user-images.githubusercontent.com/1307497/65638497-18c50200-df9b-11e9-94bc-b35816856cef.png)

Here's a screencast of me changing this option on a New Page. In the Customizer, I have the Genesis Site Layout set to `Content, Primary Sidebar`...
[View Screencast](https://share.getcloudapp.com/bLup1mlz)

Since everything seems to be working as expected I'm going to close this issue.
