### ISSUE TITLE
Repeat CSS in footer

### ISSUE THREAD

**Issue by saragreenlaw** [brandid/hello-pro#4]
.site-footer a is listed twice in the css

![Screen Shot 2019-11-05 at 3 08 20 PM](https://user-images.githubusercontent.com/6663757/68242427-7a3ab080-ffde-11e9-9dda-1e3e77f6823e.png)

**Comment by alexmustin** [comment]
This is found at:
https://github.com/brandid/hello-pro/blob/0386ca66c2b290665ee494b145263bd7c0e80506/style.css#L2254

and
https://github.com/brandid/hello-pro/blob/0386ca66c2b290665ee494b145263bd7c0e80506/style.css#L2262
